### PR TITLE
Integration Candidate 2020-03-25

### LINKED ISSUE #19: Sample app needs to release table to allow management
**Describe the bug**
Table not released after use

**To Reproduce**
Didn't test it, but likely won't be able to load a new table after sending the SAMPLE_ProcessCC command.

**Expected behavior**
Add CFE_TBL_ReleaseAddress after access of table data

**Code snips**
https://github.com/nasa/sample_app/blob/92311e71371d60d60bdde47734d8f013c065c374/fsw/src/sample_app.c#L433-L442

**Version observed on:**
 - Versions: current bundle

**Additional context**
None

**Reporter Info**
Jacob Hageman - NASA/GSFC

### PR DESCRIPTION
**Pull request by astrogeco**
**Describe the contribution**
Fixes #19 

**Testing performed**
See PR #48 
Bundle CI - [Pass](https://travis-ci.com/github/nasa/cfs/builds/158274344)

**Expected behavior changes**
 Add CFE_TBL_ReleaseAddress after access of table data

**System(s) tested on**
Bundle CI - Ubuntu: Bionic

**Contributor Info - All information REQUIRED for consideration of pull request**
 Anh Van - NASA/GSFC
Gerardo E. Cruz-Ortiz - NASA/GSFC

### CODE REVIEW

**Comment by skliper** [comment]
Are you planning to fix the "release table address" commit message?

I don't follow why this broke... was a rebase on master missed?

**Comment by skliper** [comment]
Nevermind, I see why it broke.

**Comment by jphickey** [comment]
> I don't follow why this broke... was a rebase on master missed?

The original changeset must have been based on a previous master before the name changes went in.  It's a clean merge text-wise but really a conflict.

This is precisely why we do the "integration-candidate" branch - to catch and fix this type of more subtle merge issue, before it gets to master.

**Comment by astrogeco** [comment]
Nope, this wasn't fast tracked.

**Comment by jphickey** [comment]
FWIW, I would have re-done the "integration-candidate" branch in the sample_app to clean this up.  One can merge with "--no-commit" and fix the non-detected conflict, then commit.  This will result in cleaner history.

Want me to do that?

**Comment by astrogeco** [comment]
I can squash once it works. I'll fumble my way through it. Honestly I don't mind a slightly messy history if it reflects reality.

**Comment by skliper** [comment]
I'm question "FASTTRACK" in context of the changes you are making right now that I assumed we would just review quickly as a fix to IC and push to master... or do you plan to back this change out of the IC and put it through as a new pull request (not fasttrack?)

**Comment by skliper** [comment]
Anyways, I'll stop commenting on a work in progress :)

**Comment by astrogeco** [comment]
No need to stop commenting, that's what PRs are meant for. And yes we can fast track these changes. I'll request once it passes CI or when I get stuck. What would a more detailed commit message look like?

**Comment by jphickey** [comment]
My preference is to fumble around as much as we need to in an ephemeral branch, but then clean it up for the final merge so we don't have to sort through the mess in the future.  (I hate seeing "fixup" commits in the permanent history).

At any rate, now I see you were referring to the log message on the original commit, ceb2aa7c.  This is a spot I would consider sending it back to the original author to write a better commit message.  The person doing the merges shouldn't be rewriting commit messages, they should meet the guidelines to begin with.

**Comment by jphickey** [comment]
May want to manually rebase and fix the commit message this time around, but we really should start enforcing/rejecting commits at the CCB if the logs aren't meeting the guidelines

**Comment by skliper** [comment]
Agreed, I prefer getting the commit message to meet standard prior to IC merge.

`FASTTRACK: describe change

why, and extra context if needed`

There's a few examples in most of the repos... https://github.com/nasa/sample_app/commits/master

**Comment by jphickey** [comment]
I actually don't think this is a fasttrack situation.... this is simply a merge conflict that wasn't detected by the auto-merge algorithm because it has to do with semantics, not just syntax.  This is where I would simply re-do the merge but manually fix the conflict, as it should have been if the merge algorithm was semantic-aware

**Comment by jphickey** [comment]
But since the commit message needs to be fixed anyway, just rebase it and fix both.  Then it will cleanly merge and that solves everything

**Comment by skliper** [comment]
I have no problem either way as long as there isn't a dangling commit without context

**Comment by jphickey** [comment]
Yep - rebase commit ceb2aa7, write a better commit log in the process that adheres to guidelines, then re-do integration-candidate with this instead.

Problem solved.

**Comment by astrogeco** [comment]
@skliper and @jphickey how does this look?

**Comment by jphickey** [comment]
Its OK - would have preferred to include the fix in the rebase rather than a separate commit.  But it looks like it should work.

**Pull request merged**
