### PR TITLE
Fix #78, Align use of Table/Tbl mnemonics

### LINKED ISSUE #78: Inconsistent use of TBL vs TABLE
**Describe the bug**
It seems we use TBL and TABLE interchangeably. For example 

```
  status = CFE_TBL_Register(&SAMPLE_AppData.TblHandles[0],
                              "SampleAppTable",
                              sizeof(SAMPLE_APP_Table_t),
                              CFE_TBL_OPT_DEFAULT,
                              SAMPLE_TblValidationFunc);
```

has both uses. 

**To Reproduce**
Search the sample_app directory for uses of *TBL* and *TABLE* both upper and lower case combinations exist.

**Expected behavior**
A single mnemonic for tables. TBL seems to be the default used in cFS.

**Reporter Info**
Gerardo E. Cruz-Ortiz, NASA-GSFC

### PR DESCRIPTION
**Pull request by thnkslprpt**
**Checklist**
* [x] I reviewed the [Contributing Guide](https://github.com/nasa/osal/blob/main/CONTRIBUTING.md).
* [x] I signed and emailed the appropriate [Contributor License Agreement](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) to GSFC-SoftwareRelease@mail.nasa.gov and copied cfs-program@lists.nasa.gov.

**Describe the contribution**
Fixes #78
Aligns use of Table/Tbl mnemonics in sample_app.
The macros and function parameters that used 'table' have been converted to 'tbl'.
I left the table struct (`SAMPLE_APP_Table_t`) as is for now, because this is the more common convention in cFS.

**Testing performed**
GitHub CI actions (incl. Build + Run, Unit Tests etc.) all passing successfully.

**Expected behavior changes**
No impact on behavior.

**Contributor Info**
Avi Weiss @thnkslprpt

### CODE REVIEW

**Comment by dzbaker** [comment]
CCB 3 November 2022: Preference would be to spell out "table" in all cases rather than spell it "tbl" (according to coding standards). Closing for now.

**Comment by thnkslprpt** [comment]
> CCB 3 November 2022: Preference would be to spell out "table" in all cases rather than spell it "tbl" (according to coding standards). Closing for now.

Just to clarify @dzbaker - was the preference now for the all use of 'tbl' to be converted to 'table' (and 'TBL' to 'TABLE') in sample_app, or to close that issue without any action?

**Comment by dzbaker** [comment]
> > CCB 3 November 2022: Preference would be to spell out "table" in all cases rather than spell it "tbl" (according to coding standards). Closing for now.
> 
> Just to clarify @dzbaker - was the preference now for the all use of 'tbl' to be converted to 'table' (and 'TBL' to 'TABLE') in sample_app, or to close that issue without any action?

Hi @thnkslprpt - Yes, the preferable format would ideally be 'TABLE' (typically, we'll spell out anything that is 6 or fewer characters). We discussed this at yesterday's CCB. Ideally, we would like to make them all consistent, but there's the risk that we'll miss something that will inadvertently result in something breaking somewhere, so we'd like to tackle formatting issues like these when we have more time/resources to fully test the changes.

**Comment by thnkslprpt** [comment]
> > > CCB 3 November 2022: Preference would be to spell out "table" in all cases rather than spell it "tbl" (according to coding standards). Closing for now.
> > 
> > 
> > Just to clarify @dzbaker - was the preference now for the all use of 'tbl' to be converted to 'table' (and 'TBL' to 'TABLE') in sample_app, or to close that issue without any action?
> 
> Hi @thnkslprpt - Yes, the preferable format would ideally be 'TABLE' (typically, we'll spell out anything that is 6 or fewer characters). We discussed this at yesterday's CCB. Ideally, we would like to make them all consistent, but there's the risk that we'll miss something that will inadvertently result in something breaking somewhere, so we'd like to tackle formatting issues like these when we have more time/resources to fully test the changes.

Cool no worries.
Thanks for the clarification.

**Pull request closed without merging**
