### PR TITLE
Fix #21, How to guide for setting up cmake for coverage-test

### LINKED ISSUE #21: "How to" guide for setting up cmake for coverage test
**Is your feature request related to a problem? Please describe.**
Guide for minimum setup needed for coverage test. 

**Requester Info**
Anh Van, NASA Goddard

### PR DESCRIPTION
**Pull request by avan989**
**Describe the contribution**
How to guide for minimum needed to setup cmake for coverage-test

**Testing performed**
Steps taken to test the contribution:
1. Create CMakeLists.
2. cmake .
3. make 
4. make test
5. Test ran with assert successfully 

**Contributor Info**
Anh Van, NASA Goddard

**Community contributors**
You must attach a signed CLA (required for acceptance) or reference one already submitted

### CODE REVIEW

**Comment by skliper** [comment]
CCB 20200122 - The example in #26 likely covers it,  but will review

**Comment by skliper** [comment]
@jphickey could you take a quick look at this one so we can get it out of the queue?

**Comment by jphickey** [comment]
Sorry, did not realize this was still pending, thought it was withdrawn because the actual example should be the preferred reference.

**Comment by jphickey** [comment]
Reviewing the commit within this pull request, the instructions are not accurate, so I would not recommend pulling this.  I would rather simply refer to the example to illustrate the recommended practice

**Pull request closed without merging**
